name: Process boot.img from URL

on:
  workflow_dispatch: # Allow manual triggering of the workflow
    inputs:
      boot_img_url:
        description: "URL to download the boot.img file"
        required: true
        type: string
        #default: "https://filebin.net/gp05fto9lulm3qwg/boot.img"  # Default URL if not provided

jobs:
  process-boot-img:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Download boot.img from the provided URL
      - name: Download boot.img
        run: |
          curl -L -o boot.img "${{ github.event.inputs.boot_img_url }}"
          if [ ! -f "boot.img" ]; then
            echo "Failed to download boot.img. Exiting."
            exit 1
          fi

      # Step 3: Ensure magiskboot is executable and process boot.img
      - name: Process boot.img
        continue-on-error: true
        run: |
          # Ensure magiskboot is executable
          chmod +x magiskboot
          
      # Step 4: Upload unpacked files as artifact
      - name: Upload unpacked files
        uses: actions/upload-artifact@v3
        with:
          name: unpacked-boot-img
          path: |
            ramdisk.cpio
            kernel
            dtb
            header
            *  # ou todos os arquivos extraídos pelo magiskboot


          # Run magiskboot and capture output
          ./magiskboot unpack boot.img
